### ISSUE TITLE
Run pyHYDRA without covariate_tsv

### ISSUE THREAD

**Issue by IoannaSkampardoni** [anbai106/mlni#2]
Hi. While running pyHYDRA without covariate_tsv, an error appears at the base.py line which normally reads the covariates file. From the error message 'ValueError: Invalid file path or buffer object type: <class 'int'>', I think it tries to read the covariates file but there is no such file. I attach a screenshot. Thank you.
![Read covariates file](https://user-images.githubusercontent.com/79587980/115538666-cc3fc680-a2a4-11eb-90cf-730289005515.JPG)

**Comment by anbai106** [comment]
Hi, **n_threads** is an optional argument (so does **covariate_tsv**). You gave it as mandatory. That's why pyHYDRA take **n_threads** as **covariate_tsv**, leading to your **ValueError**.

Please run this: `clustering(feature_tsv, output_dir, k_min, k_max, cv_repetition, n_threads=n_threads)`

Thanks

**Comment by IoannaSkampardoni** [comment]
Great, thank you!
