### ISSUE TITLE
data normalization and information leakage

### ISSUE THREAD

**Issue by joshleelab** [anbai106/mlni#9]
I normalized my sample data prior to running the HYDRA classifier, but it occurred to me that scaling the data prior to cross-validation can introduce data leakage because information from the entire dataset is used to determine the scaling parameters (mean and standard deviation), which then affects each fold of the cross-validation. 

Perhaps it would be better to separately scale the data in each split? 

hhm I think I was mistaken. Apologies. I see now that there is scaling being performed on the features using x = self._input.get_x().

**Comment by anbai106** [comment]
Ideally, scaling data or feature selection should always be done in nested cross validation (especially for classification and regression supervised ML). HYDRA is built on top of multiple SVMs to find disease subtypes, and I think feature scaling is done on the entire dataset. Since scaling does not involve the labels of the data, and HYDRA only uses the labels (CN and PT) to guide the final disease subtypes, I don't think this will be a big issue. But if you want to incorporate scaling into CV, I think it's doable, just adjust the code.
